roachgram/chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("" , views.chat , name="chat-page"),
    path("<str:room_name>" , views.chatRoom , name="chat-room")
]

roachgram/roachgram/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/" , include("users.urls")),
    path("" , include("feeds.urls")),

    # chat urls
    path("chats/" , include("chat.urls")),

    # user api routes
    path("api/" , include("users.api.urls")),

    # feeds api routes
    path("api/posts/" , include("feeds.api.urls"))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roachgram/chat/models.py
from django.db import models
from users.models import User

class Room(models.Model):
    name = models.CharField(max_length=256)
    sender = models.ForeignKey(User , on_delete=models.CASCADE , null=False , related_name="sender")
    receiver = models.ForeignKey(User , on_delete=models.CASCADE , null=False , related_name="receiver")

    def __str__(self) -> str:
        return self.name
    
class Message(models.Model):
    room = models.ForeignKey(Room , on_delete=models.CASCADE)
    message = models.TextField()
    sender = models.ForeignKey(User , on_delete=models.CASCADE)

    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{self.sender.username} sent to {self.room.name}'
    

class ConnectionHistory(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    is_online = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"{self.user.username} is {'Online' if self.is_online else 'Offline'}"

roachgram/chat/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.decorators import login_required
from users.models import FollowUser
from .models import Room , Message
from users.models import User
from django.http import Http404
from django.db.models import Q
from django.contrib import messages as message_generator

@login_required()
def chat(request):

    if request.method == "POST":
        reciverId = request.POST.get("receiver")
        return redirect("chat-room" , f"{request.user.id}-{reciverId}")

    followedUsers = FollowUser.objects.filter(follower=request.user)
    chats = Room.objects.filter(Q(sender=request.user) | Q(receiver=request.user))

    context = {
        "available_users_to_chat": followedUsers,
        "chats": chats
    }

    return render(request , "chatPage.html" , context)


@login_required()
def chatRoom(request , room_name):
    
    try:
        # room name is created by sender's id (logged in user) and receiver's id and like this sender-receiver
        ids = room_name.split("-")
        print(ids , request.user.id)
        # pervent user to access rooms that not in them
        if str(request.user.id) not in ids:
            message_generator.error(request , "You Don't Have Permission")
            return redirect("chat-page")
        # remove logged in user from ids list
        ids.remove(str(request.user.id))
        # 1 item will remain which is another user excep logged in user
        receiverId = ids[0]
        receiver = User.objects.get(id=receiverId)
    except User.DoesNotExist:
        raise Http404
    
    try:
        # make reverse room_name. we reverse that because there might be same room but diffrent receivers and not creating new record in db
        reveresedRoomName = room_name.split("-")[::-1]
        otherRoomName = "-".join(reveresedRoomName)
        # check if one of room names exists
        room = Room.objects.get(Q(name=room_name) | Q(name=otherRoomName))
    except Room.DoesNotExist:
        room = Room(name=room_name , sender=request.user , receiver=receiver)
        room.save()

    messages = Message.objects.filter(room=room)
    
    context = {
        "room_name": room.name,
        "receiver": receiver,
        "chat_messages": messages 
    }
    return render(request , "chatRoom.html" , context)

roachgram/chat/templates/chatPage.html
{% extends 'main.html' %}

{% block content %}
<main class="text-white">
    <header class="flex pb-5 border-b-2 border-gray-600 justify-center items-center">
        {% for follow_instance in available_users_to_chat %}
            <form method="post" action="">
                {% csrf_token %}
                <input type="text" name="receiver" hidden value="{{follow_instance.following.id}}" />
                <button class="flex hover:bg-gray-600 w-28 cursor-pointer rounded-lg p-2 flex-col justify-center items-center" type="submit">
                    <img class="aspect-square object-cover w-14 rounded-full" src="{{follow_instance.following.profile.url}}" />
                    <p class="text-gray-200 text-xs opacity-50">{{ follow_instance.following.name }}</p>
                    <a href="{% url 'user-page' follow_instance.following.username  %}" class="text-medium hover:underline">@{{ follow_instance.following.username }}</a>
                </button>
            </form>
        {% endfor %}
        {% if not available_users_to_chat %}
            <p class="text-lg text-center mt-2">Start Following People To Chat With Them</p>
        {% endif %}
    </header>
    <section class="">
            {% for chat in chats %}
            {% if chat.message_set.last %}
                <a href="{% url 'chat-room' chat.name %}" class="flex items-center gap-2 hover:bg-gray-800 px-5 py-2 cursor-pointer transition-all border-b-2 border-gray-600 hover:border-gray-800">
                    {% if chat.receiver.id != user.id %}
                        <img class="aspect-square w-16 rounded-full object-cover" src="{{chat.receiver.profile.url}}" alt="">
                        <div class="flex flex-col justify-center w-full">
                            <p class="text-lg">@{{ chat.receiver.username }}</p>
                            <p class="opacity-50 text-sm">{{ chat.receiver.name }}</p>
                        </div>
                        <div class="flex flex-col w-full">
                            <p class="opacity-50 text-sm self-end">{{ chat.message_set.last.createdAt|date:"H:i" }}</p>
                            <p class="w-full line-clamp-1">
                                {% if chat.message_set.last.sender == user %}
                                {{ chat.message_set.last.message }} (You Sent)
                                {% else %}
                                {{ chat.message_set.last.message }}
                                {% endif %}
                            </p>
                        </div>
                    {% else %}
                        <img class="aspect-square w-16 rounded-full object-cover" src="{{chat.sender.profile.url}}" alt="">
                        <div class="flex flex-col justify-center w-full">
                            <div class="text-lg flex items-center gap-2">
                                <p>@{{ chat.sender.username }}</p>
                                {% if chat.sender.connectionhistory_set.last.is_online %}   
                                    <span class="bg-green-600 text-white text-center mt-1 text-xs rounded-lg w-fit px-2 py-0.5 font-semibold">Chatting</span>
                                {% endif %}
                            </div>
                            <p class="opacity-50 text-sm">{{ chat.sender.name }}</p>
                        </div>
                        <div class="flex flex-col w-full">
                            <p class="opacity-50 text-sm self-end">{{ chat.message_set.last.createdAt|date:"H:i" }}</p>
                            <p class="w-full line-clamp-1">
                                {% if chat.message_set.last.sender == user %}
                                {{ chat.message_set.last.message }} (You Sent)
                                {% else %}
                                {{ chat.message_set.last.message }}
                                {% endif %}
                            </p>
                        </div>
                    {% endif %}
                {% endif %}
                </a>
            {% endfor %}
    </section>
    {% if not chats %}
        <p class="text-center text-2xl mt-80">You Didn't Chat Anyone</p>
    {% endif %}
</main>

{% endblock content %}

roachgram/chat/templates/chatRoom.html
{% extends 'main.html' %}

{% block content %}
<main class="">
    <section class="flex justify-center items-center">
        <header id="user-banner" class="w-[616px] fixed bg-gray-800  top-0 flex p-4 text-white gap-3 px-10">
            <img src="{{receiver.profile.url}}" class="aspect-square object-cover w-20 rounded-full" />
            <div class="flex flex-col justify-center">
                <a href="{% url 'user-page' receiver.username %}" class="hover:underline">@{{ receiver.username }}</a>
                <p class="text-xs opacity-40">{{ receiver.name }}</p>
            </div>
            
        </header>

        <div id="messages-parent" class="mt-28 p-5 h-full w-full flex flex-col gap-5 mb-20">
            {% for chat_message in chat_messages %}
                {% if chat_message.sender != user %}
                <div class="receive flex w-[320px] items-start gap-2.5 self-start">
                    <img class="w-8 h-8 rounded-full aspect-square object-cover" src="{{receiver.profile.url}}" alt="Jese image">
                    <div class="flex flex-col gap-1 w-full max-w-[320px]">
                        <div class="flex items-center space-x-2 rtl:space-x-reverse">
                            <span class="text-sm font-semibold text-gray-900 dark:text-white">{{receiver.name}}</span>
                            <span class="text-sm font-normal text-gray-500 dark:text-gray-400">{{chat_message.createdAt|date:"H:i"}}</span>
                        </div>
                        <div class="flex flex-col leading-1.5 p-4 border-gray-200 bg-gray-100 rounded-e-xl rounded-es-xl dark:bg-gray-900">
                            <p class="text-sm font-normal text-gray-900 dark:text-white">{{chat_message.message}}</p>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="send flex w-[320px] items-start self-end flex flex-row-reverse gap-2.5">
                    <img class="w-8 h-8 rounded-full float-right aspect-square object-cover" src="{{user.profile.url}}" alt="">
                    <div class="flex flex-col gap-1">
                        <div class="flex self-end items-center space-x-2 rtl:space-x-reverse">
                            <span class="text-sm font-normal text-gray-500 dark:text-gray-400">{{chat_message.createdAt|date:"H:i"}}</span>
                            <span class="text-sm font-semibold text-gray-900 dark:text-white">{{ user.name }}</span>
                        </div>
                        <div class="flex flex-col leading-1.5 p-4 border-gray-200 bg-gray-100 rounded-l-xl rounded-r-xl rounded-tr-none dark:bg-gray-900">
                            <p class="text-sm font-normal text-gray-900 dark:text-white">{{chat_message.message}}</p>
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>

        <form id="message-form" class="fixed bottom-10 m-auto flex justify-center items-center">
            <div class="px-4 py-2 bg-gray-800 flex h-14 max-h-32 justify-center w-[400px] rounded-xl gap-2 items-center">
                <textarea id="message-box" type="text" class=" resize-none outline-none bg-transparent  max-h-full w-full text-white" placeholder="Write New Message"></textarea>
                <button type="submit">
                    <img width="24" height="24" src="https://img.icons8.com/material-rounded/24/ffffff/sent.png" alt="sent"/>
                </button>
            </div>
        </form>
    </section>
    
</main>
<script>
    window.scrollTo(0, document.body.scrollHeight);
    const chatSocket = new WebSocket("ws://" + window.location.host + "/chats/{{room_name}}/");
      chatSocket.onopen = function (e) {
        console.log("The connection was setup successfully !");
        chatSocket.send(JSON.stringify({
            username: "{{receiver.username}}",
            type: "check_user_status"
        }))
      };
      chatSocket.onclose = function (e) {
        console.log("Something unexpected happened !");
      };
      document.getElementById("message-form").addEventListener("submit" , function(e){
        e.preventDefault()
        const textMessage = document.getElementById("message-box").value
        chatSocket.send(JSON.stringify({
            type: "message",
            message: textMessage,
            sender: "{{user.username}}"
        }))
      })

    // listens for response from server
      chatSocket.addEventListener("message" , e =>{
        const data = JSON.parse(e.data)
        console.log(data)
        switch (data["type"]){
            case "user_status":
                
                const username = data["username"]
                const isOnline = data["is_online"]
                
                const userBanner = document.getElementById("user-banner")
                const ele = document.createElement("span")
                if (username == '{{receiver.username}}' && userBanner.children[1].children.length <= 3) {
                    
                    
                    ele.className = "user-status bg-green-600 text-white text-center text-xs rounded-lg mt-2 w-fit px-4 py-1 font-semibold"
                    if (isOnline) {
                        ele.textContent = 'Chatting'
                        userBanner.children[1].appendChild(ele) 
                    }
                    
                    else if (userBanner.children[1].children.length == 3){
                        userBanner.children[1].querySelector(".user-status").remove()
                    }   
                }
                break;
            case "message":
                let sender = data["sender"]
                let message = data["message"]

                if (sender == '{{user.username}}') {
                    document.getElementById("message-box").value = ""
                }

                // showing messages
                const receiveElement =`
                <div class="receive flex w-[320px] items-start gap-2.5 self-start">
                        <img class="w-8 h-8 rounded-full aspect-square object-cover" src="{{receiver.profile.url}}" alt="Jese image">
                        <div class="flex flex-col gap-1 w-full max-w-[320px]">
                            <div class="flex items-center space-x-2 rtl:space-x-reverse">
                                <span class="text-sm font-semibold text-gray-900 dark:text-white">{{receiver.name}}</span>
                                <span class="text-sm font-normal text-gray-500 dark:text-gray-400">{% now "H:i" %}</span>
                            </div>
                            <div class="flex flex-col leading-1.5 p-4 border-gray-200 bg-gray-100 rounded-e-xl rounded-es-xl dark:bg-gray-900">
                                <p class="text-sm font-normal text-gray-900 dark:text-white">${message}</p>
                            </div>
                        </div>
                </div>`

                const sendElement = `
                    <div class="send flex w-[320px] items-start self-end flex flex-row-reverse gap-2.5">
                        <img class="w-8 h-8 rounded-full float-right aspect-square object-cover" src="{{user.profile.url}}" alt="">
                        <div class="flex flex-col gap-1">
                            <div class="flex self-end items-center space-x-2 rtl:space-x-reverse">
                                <span class="text-sm font-normal text-gray-500 dark:text-gray-400">{% now "H:i" %}</span>
                                <span class="text-sm font-semibold text-gray-900 dark:text-white">{{ user.name }}</span>
                            </div>
                            <div class="flex flex-col leading-1.5 p-4 border-gray-200 bg-gray-100 rounded-l-xl rounded-r-xl rounded-tr-none dark:bg-gray-900">
                                <p class="text-sm font-normal text-gray-900 dark:text-white">${message}</p>
                            </div>
                        </div>
                    </div>
                `

                var messageParent = document.getElementById("messages-parent")
                if (sender != '{{user.username}}') {
                    messageParent.innerHTML += receiveElement
                }
                else{
                    messageParent.innerHTML += sendElement
                }
                window.scrollTo(0, document.body.scrollHeight);
                break;
        }
        
        
    })
</script>
{% endblock content %}