roachgram/chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("" , views.chat , name="chat-page"),
    path("<str:room_name>" , views.chatRoom , name="chat-room")
]

roachgram/roachgram/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/" , include("users.urls")),
    path("" , include("feeds.urls")),

    # chat urls
    path("chats/" , include("chat.urls")),

    # user api routes
    path("api/" , include("users.api.urls")),

    # feeds api routes
    path("api/posts/" , include("feeds.api.urls"))

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

roachgram/users/api/urls.py
from django.urls import path
from . import viewsets


from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

urlpatterns = [
    path("auth/register/" , viewsets.RegisterUser.as_view() , name="api-register"),    
    path("user" , viewsets.UserView.as_view() , name="api-user"),    
    path("auth/edit-user/" , viewsets.UpdateUser.as_view() , name="api-update-user"),
    path("auth/change-password/" , viewsets.ChangePassword.as_view() , name="api-change-password"),
    path("users" , viewsets.AllUsers.as_view() , name="all-users"),
    path("users/follow/" , viewsets.FollowView.as_view() , name="follow-user"),
    path("users/notifications/" , viewsets.Notifications.as_view() , name="api-notifications"),
    path("users/<str:username>" , viewsets.OneUser.as_view() , name="one-user"),
    path("users/<str:username>/likes/" , viewsets.OneUserLikes.as_view() , name="api-user-likes"),
    path("users/<str:username>/replies/" , viewsets.OneUserReplies.as_view() , name="api-user-replies"),
    path("users/<str:username>/followers/" , viewsets.OneUserFollowers.as_view() , name="api-users-followers"),
    path("users/<str:username>/followings/" , viewsets.OneUserFollowings.as_view() , name="api-users-followings"),
    
    # JWT authentication
    path('auth/login', viewsets.MyToken.as_view(), name='token_obtain_pair'),
    path('auth/login/refresh', TokenRefreshView.as_view(), name='token_refresh'),

]

roachgram/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authViews

urlpatterns = [
    # auth routes
    path("register" , views.registeration , name="register-user"),
    path("login" , authViews.LoginView.as_view(template_name="login.html" , redirect_authenticated_user=True) , name="login-user"),
    path("logout" , authViews.LogoutView.as_view() , name="logout-user"),

    # profile route
    path("profile/",  views.updateUser , name="update-user"),

    # notification route
    path("notifications/" , views.userNotifications , name="notification-page"),

    # change password route
    path("change-password" , views.changesPassword , name="change-password"),

    # password reset
    path("password-reset-done" , authViews.PasswordResetDoneView.as_view(template_name="password_reset_done.html") , name="password-reset-done"),
    path("password-reset" , views.ResetPassword.as_view() , name="password-reset"),
    path("password-reset-confirm/<uidb64>/<token>/" , authViews.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html") , name="password_reset_confirm"),
    path("password-reset-complete" , authViews.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html") , name="password_reset_complete"),

    path("<str:username>/" , views.userPage , name="user-page"),
    path("<str:username>/likes" , views.userPageLikes , name="user-page-likes"),
    path("<str:username>/replies" , views.userPageReplies , name="user-page-replies"),
    path("<str:username>/follow/" , views.followUser , name="follow-user"),
    path("<str:username>/unfollow/" , views.unfollowUser , name="unfollow-user"),
    path("<str:username>/followers" , views.userFollowers , name="user-followers-page"),
    path("<str:username>/followings" , views.userFollowings , name="user-followings-page"),
    
    
    
]

roachgram/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import auto_prefetch
from datetime import datetime
# Create your models here.

def user_profile_directory(instance , filename):
    return f"{instance}/{filename}"

class User(AbstractUser):
    name    = models.CharField(max_length=255 , blank=True , null=True)
    email   = models.EmailField(unique=True)
    about   = models.TextField(max_length=255 , blank=True , null=True)
    profile = models.ImageField(upload_to=user_profile_directory , default="default-profile.png" , blank=True , null=True)

    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.username
    
    def get_followers_and_followings_count(self):
        followersCount = FollowUser.objects.filter(following=self).count()
        followingsCount = FollowUser.objects.filter(follower=self).count()

        return {
            "followersCount": followersCount,
            "followingsCount": followingsCount
        }
    
    def get_all_user_posts(self):
        from feeds.models import Post  
        return Post.objects.filter(user=self).order_by("-createdAt")
    
    def get_by_natural_key(self, username):
        return self.get(username__iexact=username)

class FollowUser(models.Model):
    follower = auto_prefetch.ForeignKey(User , on_delete=models.CASCADE , related_name="followers")
    following = auto_prefetch.ForeignKey(User , on_delete=models.CASCADE , related_name="followings")
    createdAt = models.TimeField(auto_now_add=True , blank=True , null=True)
    updatedAt = models.TimeField(auto_now=True , blank=True , null=True)


    def __str__(self):
        return f"{self.follower.username} following {self.following.username}"
    

class NotificationType(models.Model):
    TYPE_CHOICES = (
        ("LIKE" , "Like"),
        ("COMMENT" , "Comment"),
        ("MENTION" , "Mention"),
        ("FOLLOW" , "Follow"),
        ("MESSAGE" , "Message"),
        ("BOOKMARK" , "Bookmark")
    )
    type = models.CharField(
        choices=TYPE_CHOICES,
        max_length=128
    )
    text = models.TextField()

    def __str__(self) -> str:
        return f"{self.type} - {self.text}"

class Notification(models.Model):
    user_to_notif = models.ForeignKey(User , on_delete=models.CASCADE)
    notif_type = models.ForeignKey(NotificationType , on_delete=models.CASCADE)
    triggered_by = models.ForeignKey(User , on_delete=models.CASCADE , related_name="triggered_by")
    seen = models.BooleanField(default=False)
    createdAt = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"notification for {self.user_to_notif.username}"

roachgram/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , UserChangeForm
from .models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout , Row , Column , Field , Submit

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    name = forms.CharField(max_length=255)
    class Meta:
        model = User
        fields = ("profile" , "name" , "username", "email" , "password1" , "password2" , "about")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Row(
                Column(Field("profile"))
            ),
            Row(
                Column(Field("name"), css_class="px-2"),   
                Column(Field("username"), css_class="px-2"),   
                Column(Field("email"), css_class="px-2"),   
            ),
            Row(
                Column(Field("password1"), css_class="px-2"),   
                Column(Field("password2"), css_class="px-2")
            ),
            Row(
                Column(Field("about"), css_class="resize"),   
            ),
            Submit('submit', 'Submit', css_class='bg-green-500 px-6 py-2 text-white rounded-lg cursor-pointer')
            
        )


class UpdateUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("profile",'name',"username","email","about")
    name = forms.CharField(max_length=255 , widget=forms.TextInput(attrs={"class": "bg-black"}))
    profile = forms.ImageField(widget=forms.FileInput(attrs={"class": "hidden" , "onchange": "previewProfile(this)"}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column(Field("profile"))
            ),
            Row(
                Column(Field("name"), css_class="px-2 w-1/3"),   
                Column(Field("username"), css_class="px-2 w-1/3"),   
                Column(Field("email"), css_class="px-2 w-1/3 text-white"),   
            ),
            Row(
                Column(Field("about"), css_class="resize"),   
            ),
            Submit('submit', 'Update', css_class='bg-green-500 px-6 my-6 py-2 text-white rounded-lg cursor-pointer')
            
        )

roachgram/users/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render , redirect , get_object_or_404
from django.contrib.auth.decorators import login_required 
from .models import User , FollowUser , Notification , NotificationType
from django.contrib import messages
from .forms import RegisterForm , UpdateUserForm
from django.contrib.auth import login
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy
from feeds.models import Post , Like , Comment
from django.db.models import Q
from itertools import chain
from operator import attrgetter

def registeration(request):
    if request.method == "POST":
        form = RegisterForm(request.POST , request.FILES)
        if (form.is_valid()):
            registeredUser = form.save()
            login(request , registeredUser)
            
            messages.success(request , "your account created succcessfully")
            return redirect("home-page")
    
    else:
        form = RegisterForm()

    context = {
        "form": form,
        "htmlTitle": "Register New Account"
    }
    return render(request , "register.html" , context)


def userPage(request , username):
    
    try:
        user = User.objects.get(username=username)
        userPosts = Post.objects.filter(Q(user=user) & Q(isReply=False)).order_by("-createdAt")
    except User.DoesNotExist:
        raise Http404



    context = {
        "account": user,
        "posts": userPosts,
        "htmlTitle": f"{username}'s Page"
    }

    return render(request , "userPage.html" , context)



def userPageLikes(request , username):
    try:
        user = User.objects.get(username=username)
        condition = Q(post__in=Like.objects.filter(user=user))
        likedPosts = Post.objects.filter(condition & Q(isReply=False))
        likedComments = Comment.objects.filter(condition)
        result = sorted(list(chain(likedPosts , likedComments)) , key=attrgetter("createdAt") , reverse=True)
    except User.DoesNotExist:
        raise Http404



    context = {
        "account": user,
        "posts": result
    }


    return render(request , "userPage.html" , context)


def userPageReplies(request , username):
    try:
        user = User.objects.get(username=username)
        repliedPosts = Comment.objects.filter(user=user).order_by("-createdAt")

    except User.DoesNotExist:
        raise Http404
    
    context = {
        "account": user,
        "posts": repliedPosts
    }

    return render(request , "userPage.html" , context)

def userFollowers(request , username):
    user = get_object_or_404(User,username=username)
    followers = User.objects.filter(followers__in=FollowUser.objects.filter(following=user))

    context = {
        "users": followers
    }

    return render(request , "followersOrFollowings.html" , context)

def userFollowings(request ,username):
    user = get_object_or_404(User,username=username)
    followings = User.objects.filter(followings__in=FollowUser.objects.filter(follower=user))
    
    context = {
        "users": followings
    }

    return render(request , "followersOrFollowings.html" , context)

@login_required()
def updateUser(request):
    if request.method == "POST":
        form = UpdateUserForm(request.POST, request.FILES , instance=request.user)
        
        if form.is_valid():
            form.save()
            messages.success(request , "You Profile Changed Successfullly")
    
    else:
        form = UpdateUserForm(instance=request.user)
    
    return render(request , "profile.html" , { "form": form })

@login_required()
def followUser(request , username):

    # check if user exists in database
    
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        messages.error(request , "user not found")
        return redirect("user-page" , username)
    
    if (request.user.id == user.id):
        messages.error(request , "you can't follow yourself")
        return redirect("user-page" , user.username)  
    
    # checks for user if it's already following
    isFollowing = FollowUser.objects.filter(follower=request.user, following = user).exists()


    if (isFollowing):
        messages.error(request , f"you already following @{user.username}")
        return redirect("user-page" , user.username)

    # if user not following already it creats a record in database
    FollowUser.objects.create(follower=request.user , following=user)
    messages.success(request , f"you are now following @{user.username}")
    return redirect("user-page" , user.username)


@login_required()
def unfollowUser(request , username):

    # check if user exists in database
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        messages.error(request , "user not found")
        return redirect("user-page" , "reza")
    

    # checks for user if it's already following
    isFollowing = FollowUser.objects.filter(follower=request.user, following = user).exists()


    if (not isFollowing):
        messages.error(request , f"you'r not following @{user.username} so you can't unfollow")
        return redirect("user-page" , user.username)

    # if user not following already it creats a record in database
    FollowUser.objects.get(follower=request.user , following=user).delete()
    messages.success(request , f"you are now not following @{user.username}")
    return redirect("user-page" , user.username)

@login_required()
def userNotifications(request):
    notifications = Notification.objects.filter(user_to_notif=request.user).order_by("-createdAt")
    context = {
        "notifications": notifications
    }

    return render(request , "notifications.html" , context)

@login_required
def changesPassword(request):
    
    if request.method == "GET":
        return render(request , "changePassword.html")

    user = User.objects.get(username=request.user.username)

    oldPass = request.POST.get("oldPassword")
    newPass = request.POST.get("newPassword")    

    if user.check_password(oldPass):
        user.set_password(newPass)
        user.save()
        update_session_auth_hash(request, user)
        messages.success(request , "Your Password Changed Successfully")
        return redirect("update-user")
    
    messages.error(request , "The Old Password Does Not Match")
    return redirect("change-password")


class ResetPassword(PasswordResetView):
    template_name = "password_reset.html"
    email_template_name = "password_reset_email.html"
    subject_template_name = "password_reset_subject.txt"
    success_url = reverse_lazy("password-reset-done")

roachgram/users/templates/changePassword.html
{% extends 'main.html' %}

{% block content %}
<h1 class="text-2xl text-center font-medium text-white mt-10">Set Your New Password</h1>
<form action="" method="post" class="flex flex-col text-white gap-10 py-10 justify-center items-center">
    {% csrf_token %}
    <div class="flex text-white gap-5 justify-center items-center">
        <div class="flex flex-col">
            <label for="oldPassword">Old Password</label>
            <input type="password" id="oldPassword" name="oldPassword" class="bg-transparent border-2 border-gray-400 outline-none rounded-lg px-4 py-1" />
        </div>
        <div class="flex flex-col">
            <label for="newPassword">New Password</label>
            <input type="password" id="newPassword" name="newPassword" class="bg-transparent border-2 border-gray-400 outline-none rounded-lg px-4 py-1" />
        </div>
    </div>
    <button class="text-white bg-green-600 rounded-lg px-4 py-2">Change Password</button>
</form>
{% endblock content %}

roachgram/users/templates/followersOrFollowings.html
{% extends 'main.html' %}
{% load customTemplateTags %}

{% block content %}

{% for foundedUser in users %}
<div class="flex justify-between px-10 py-10 items-center text-white gap-2">
    
    <a href="{% url 'user-page' username=foundedUser.username %}" class="flex justify-center items-center gap-2">
        <img class="aspect-square w-14 rounded-full object-cover" src="{{foundedUser.profile.url}}" alt="">
        <div class="flex flex-col ">
            <p>{{ foundedUser.name }}</p>
            <p class="opacity-50">@{{ foundedUser.username }}</p>
        </div>
    </a>

    {% if user.is_authenticated and user.id != foundedUser.id %}
        {% followedTheUser user foundedUser as isfollowingTheUser %}
        {% if not isfollowingTheUser %}
        <form onsubmit="sendNotif('{{userToFollow.username}}' , 'follow')" class="-ml-16" action="{% url 'follow-user' username=foundedUser.username %}">
            <button class="px-8 w-32 py-0.5 font-medium bg-white text-black rounded-full" type="submit">
                Follow
            </button>
        </form>
        {% else %}

        <form class="" action="{% url 'unfollow-user' username=foundedUser.username %}">
            <button class="px-8 w-32 py-0.5 font-medium bg-transparent text-white border-2 border-gray-600 rounded-full" type="submit">
                Unfollow
            </button>
        </form>

        {% endif %}
    {% endif %}
    
</div>
<hr class="border-gray-600">
{% endfor %}
{% if not users %}
<h1 class="text-white text-center mt-80 text-3xl">There Are No Users In Here</h1>
{% endif %}
{% endblock %}

roachgram/users/templates/login.html
{% load tailwind_filters %}
{% load crispy_forms_tags %}
<script src="https://cdn.tailwindcss.com"></script>
	{% block content %}       

	<h1 class="text-center text-2xl font-semibold font-sans mt-10">Login To Your Account</h1>
	<div class="container py-5 mt-10 flex flex-col justify-center items-center">
		<form method="POST" action="" class="px-8 bg-gray-200 py-4 w-[500px] flex justify-center items-center flex-col rounded-xl">
			{% csrf_token %}
			{{ form|crispy }}      
            <button class="mb-4 bg-blue-500 rounded-lg text-white px-6 py-2" type="submit">Login</button>              
        </form>
        <a class="text-blue-400 underline" href="{% url 'register-user' %}">Don't Have An Account? Signup Instead.</a>
        <a class="text-blue-400 underline" href="{% url 'password-reset' %}">Forgot Your Password? Reset Password.</a>
	</div>

{% endblock %}

roachgram/users/templates/notifications.html
{% extends "main.html" %}

{% block content %}
<h1 class="text-2xl text-white font-semibold text-center my-4">Your Notifications</h1>
<section class="text-white">
    {% for notification in notifications %}
        <div class="border-b-2 relative {% if notification.seen %} border-gray-500 hover:border-gray-800 hover:bg-gray-800 {% else %} hover:bg-gray-600 bg-gray-800 border-gray-600 hover:border-gray-600 {% endif %} transition-all  flex items-center gap-2 p-5">
            {% if not notification.seen %}
                <span class="bg-blue-500 rounded-lg text-xs mr-2 px-2 py-1 text-white">New</span>
            {% endif %}
            <img class="aspect-square w-16 rounded-full object-cover" src="{{notification.triggered_by.profile.url}}" />
            <div class="flex flex-col justify-center">
                <a class="hover:underline text-lg" href="{% url 'user-page' notification.triggered_by.username %}">@{{ notification.triggered_by.username }}</a>
                <p class="text-white opacity-50 text-sm">{{ notification.triggered_by.name }}</p>
            </div>
            <p class="text-base ml-5 capitalize">{{notification.triggered_by.name}} {{ notification.notif_type.text }}</p>
            <p class="text-xs absolute bottom-2 right-5 font-semibold opacity-50">{{ notification.createdAt|timesince }} ago</p>
            <div class="absolute right-10">
                {% if notification.notif_type.type == "FOLLOW" %}
                <svg fill="#1d77d7" width="30px" height="30px" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg" stroke="#1d77d7">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"/>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"/>
                    <g id="SVGRepo_iconCarrier"> <path d="M2.002 27.959c0-0.795 0.597-1.044 0.835-1.154l8.783-4.145c0.63-0.289 1.064-0.885 1.149-1.573s-0.193-1.37-0.733-1.803c-2.078-1.668-3.046-5.334-3.046-7.287v-4.997c0-2.090 3.638-4.995 7.004-4.995 3.396 0 6.997 2.861 6.997 4.995v4.998c0 1.924-0.8 5.604-2.945 7.292-0.547 0.43-0.831 1.115-0.749 1.807 0.082 0.692 0.518 1.291 1.151 1.582l2.997 1.422 0.494-1.996-2.657-1.243c2.771-2.18 3.708-6.463 3.708-8.864v-4.997c0-3.31-4.582-6.995-8.998-6.995s-9.004 3.686-9.004 6.995v4.997c0 2.184 0.997 6.602 3.793 8.846l-8.783 4.145s-1.998 0.89-1.998 1.999v3.001c0 1.105 0.895 1.999 1.998 1.999h21.997v-2l-21.996 0.001v-2.029zM30.998 25.996h-3v-3c0-0.552-0.448-1-1-1s-1 0.448-1 1v3h-3c-0.552 0-1 0.448-1 1s0.448 1 1 1h3v3c0 0.552 0.448 1 1 1s1-0.448 1-1v-3h3c0.552 0 1-0.448 1-1s-0.448-1-1-1z"/> </g>
                </svg>
                {% elif notification.notif_type.type == "LIKE" %}
                <svg class="text-center h-9 w-8" fill="red" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="red" viewBox="0 0 24 24"><path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path></svg>
                {% elif notification.notif_type.type == "BOOKMARK" %}
                <svg class="text-center h-9 w-8" fill="black" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="black" viewBox="0 0 24 24"><path d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z"></path></svg>
                {% elif notification.notif_type.type == "COMMENT" %}
                <svg class="text-center h-9 w-8" fill="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="white" viewBox="0 0 24 24"><path d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path></svg>
                {% endif %}
            </div>
        </div>
    {% endfor %}
    {% if not notifications %}
        <p class="text-center mt-80 text-2xl">You Don't Have Any Notifications</p>
    {% endif %}
</section>

<script>
    localStorage.removeItem("notif_count")

    "{% if notifications %}"
        const notifSeenSocket = new WebSocket("ws://" + window.location.host + "/notification/{{user.username}}/{{notifications.first.id}}/seen/")
        notifSeenSocket.onopen = e =>{
            console.log("NotifSeenSocket in open")
            notifSeenSocket.send(JSON.stringify())
        }
        notifSeenSocket.onclose = e => {
            console.log("NotifSeenSocket in close")
        }
    "{% endif %}"
</script>

{% endblock content %}

roachgram/users/templates/password_reset.html
{% load tailwind_filters %}
{% load crispy_forms_tags %}
<script src="https://cdn.tailwindcss.com"></script>
    <div class="my-3 p-3">
        <div class="container">
            <div class="flex justify-center items-center py-10">
                <div class="flex flex-col justify-center items-center">
                    <div class="w-fit bg-gray-300 rounded-lg px-20 py-10 flex flex-col justify-center items-center gap-10">
                        <div class="justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="text-center text-2xl font-medium">Forgot Password?</h3>
                        </div>
                        <div class="">
                            <form method="post" action="" class="w-64 flex-col justify-center items-center">
                                {% csrf_token %}
                                {{ form|crispy }}
                
                        
                    
                                <button type="submit" class="bg-blue-500 ml-[85px] mt-10 text-white rounded-lg px-4 py-2">Submit
                                </button>
                            </form>
                        </div>
                        <div class="text-center">
                            <div class="flex flex-col">
                                <a href="{% url 'register-user' %}" class="text-blue-400 underline">Create A New Account</a><br><br>
                                <a href="{% url 'login-user' %}" class="text-blue-400 underline">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>

roachgram/users/templates/password_reset_complete.html
<script src="https://cdn.tailwindcss.com"></script>
<div class="container my-3 p-3">
    <div class="flex justify-center items-center">
        <div class="">
            <div class="shadow-lg border-0 rounded-lg mt-0 mb-3">
                <div class="bg-green-300 px-10 py-10 rounded-lg text-xl mt-20 capitalize">
                    Your password has been set. You may go ahead and <a class="text-blue-600" href="{% url 'login-user' %}">Login Here</a>
                </div>
            </div>
        </div>
    </div>
</div>

roachgram/users/templates/password_reset_confirm.html
{% load tailwind_filters %}
{% load crispy_forms_tags %}
<script src="https://cdn.tailwindcss.com"></script>
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="flex items-center justify-center mt-20">
                <div class="w-3/5 ">
                    {% if validlink %}
                        <div class="flex bg-gray-200 flex-col justify-center items-center shadow-lg border-0 rounded-lg mt-0 mb-3  px-20 py-10 rounded-xl">
                            <div class="card-header justify-content-center">
                              <h3 class="text-3xl my-4 text-center">Reset Your Password</h3>
                            </div>
                            <form class="flex  flex-col" action="" method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button class="bg-blue-500 w-fit m-auto rounded-lg px-4 py-2 text-white" type="submit">
                                    Reset Password
                                </button>
                            </form>
                        </div>
                    {% else %}
                    <div class="text-red-600">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

roachgram/users/templates/password_reset_done.html
<script src="https://cdn.tailwindcss.com"></script>
<div class="container my-3 p-3">
    <div class="flex justify-center items-center">
        <div class="">
            <div class="shadow-lg border-0 rounded-lg mt-0 mb-3">
                <div class="bg-green-300 w-[700px] text-center  px-10 py-10 rounded-lg text-xl mt-20 capitalize">
                    We've emailed you instructions for setting your password,
                    if an account exists with the email you entered. You should receive them shortly.
                    If you don't receive an email,
                    please make sure you've entered the address you registered with, and check your spam folder.
                </div>
            </div>
        </div>
    </div>
</div>

roachgram/users/templates/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} RoachGram Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Amirali AKA Roach,
  The Developer
{% endautoescape %}

roachgram/users/templates/profile.html
{% extends 'main.html' %}
{% load static %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}

{% block content %}
<style>
    #id_name{
        color: white;
        background-color: transparent;
    }
    #id_username{
        color: white;
        background-color: transparent;
    }
    #id_email{
        color: white;
        background-color: transparent;
    }
    #id_about{
        color: white;
        background-color: transparent;
    }
</style>
<script>
    const previewProfile = (e) => {
        const file = e.files[0]
  


        const blob = URL.createObjectURL(file)     
        const profile = document.querySelector(".profile")  
        profile.src = blob
}
</script>
<form enctype="multipart/form-data" method="post" class="flex pt-5 flex-col justify-center items-center" action="">
    <label for="id_profile" class="cursor-pointer">
        <img style="height:9rem; width:9rem;" id="profile" class="md profile rounded-full aspect-square object-cover relative" src="{{user.profile.url}}" alt="">
    </label>
    <a class="mt-5 text-blue-400 underline" href="{% url 'change-password' %}">Change Password</a>
    {% csrf_token %}
    {% crispy form %}
    
</form>
{% endblock content %}

roachgram/users/templates/register.html
{% load tailwind_filters %}
{% load crispy_forms_tags %}
<script src="https://cdn.tailwindcss.com"></script>
	{% block content %}          

	<!--Register--> 
	<div class="container py-5 flex flex-col justify-center items-center">
		<form enctype="multipart/form-data" method="POST" action="" class="w-[750px] rounded-xl border-2 px-8 py-4 bg-gray-200 flex justify-center items-center flex-col">
			{% csrf_token %}
			{% crispy form %}                    
            <a class="text-blue-400 underline" href="{% url 'login-user' %}">If You Already Have An Account, Login Instead.</a>
		</form>
		
	</div>

{% endblock %}